<?php 

function demo_menu(){
	$items = array();
	$items['custom/demo/index'] = array(
		'title'            => t('Hello World'),
		'page callback'    => 'demo_index_action',
		'access arguments' => array('access content'),
		'type'             => MENU_LOCAL_TASK,
	);
	$items['demo/form'] =array(
		'title'            => t('Demo Form'),
		'page callback' => array( 'drupal_get_form'),
		'page arguments' => array('demo_form'),
		'access arguments' => array('access content'),
		'type'             => MENU_LOCAL_TASK,
	);
	return $items;
}

function demo_theme($existing, $type, $theme, $path) {
	 return array(
		'demo_index' => array(
			'template' => 'demo_index'
		),
		'demo_form' => array(
			'render element' => 'form',
			'path' => drupal_get_path('module', 'demo') ,
			'template' => 'demo-form',
		),
	);
}
function demo_index_action(){
	 return theme('demo_index', array());
}

/*
 * implements hook_form($form, &$form_state)
 */
function demo_form($form, &$form_state) {
  $form['name'] = array(
      '#type' => 'textfield',
      '#title' => t('Enter your name'),
      '#default_value' => '',
      '#required' => TRUE
  );
  $form['phone'] = array(
      '#type' => 'textfield',
      '#title' => t('Enter your phone number'),
      '#default_value' => '',
      '#required' => TRUE
  );
  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  
  return $form;
}

/*
 * impletements hook_form_validate($form, &$form_state)
 */
function demo_form_validate($form, &$form_state){
    //I'm going to validate only phone number for this demo
    $phone = $form_state['values']['phone'];
    if(!preg_match("/^[0-9]{3}-[0-9]{4}-[0-9]{4}$/", $phone)) {
        form_set_error('phone', 'Please enter a valid phone number');
    }
}

/*
 * implements hook_form_submit($form, &$form_state)
 */
function demo_form_submit($form, &$form_state){
    $name = $form_state['values']['name'];
    $phone = $form_state['values']['phone'];
    drupal_set_message(t('You have entered @name and @phone', array('@name' => $name, '@phone' => $phone)));
}